export interface TeamMember {
  id: string;
  name: string;
  handle: string;
  image: string;
  category: string;
  statusBadge: "OFFICIAL WORLD ACCOUNT" | "HOUSE FACE / PUBLIC MASCOT" | "EARLY OFFICIAL BADGE" | "ECOSYSTEM CALL" | "WORLD-ALIGNED" | "CONFIRMED BADGE" | "BADGE  VERIFY LIVE" | "TEMPORARY / NOT WORLD STAFF";
  followers?: string;
  bio: string;
  worldContext: string;
  xUrl: string;
  sectionId: "official" | "house-face" | "first-wave" | "ecosystem-call" | "world-aligned" | "solana-ct" | "other-affiliates" | "temporary-support";
  isFeatured?: boolean;
}

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "world_xyz",
    name: "World",
    handle: "@world_xyz",
    image: "/Team/world_xyz.jpg",
    category: "OFFICIAL WORLD ACCOUNT",
    statusBadge: "OFFICIAL WORLD ACCOUNT",
    bio: "The official X account for World Prediction Markets.",
    worldContext: "Central reference account for World's affiliation badge distribution campaign on X.",
    xUrl: "https://x.com/world_xyz",
    sectionId: "official",
    isFeatured: true,
  },
  {
    id: "vibnorman",
    name: "Vib Norman",
    handle: "@VibNorman",
    image: "/Team/vibnorman.jpg",
    category: "HOUSE FACE / PUBLIC MASCOT",
    statusBadge: "HOUSE FACE / PUBLIC MASCOT",
    followers: "~1.6K",
    bio: "Solana. (United Kingdom)",
    worldContext: "Only person World publicly pointed to by name as its employee on 5 July 2026: \"world only has one employee and his name is @vibnorman.\" British World-facing persona / frontman.",
    xUrl: "https://x.com/VibNorman",
    sectionId: "house-face",
    isFeatured: true,
  },
  {
    id: "sollunix",
    name: "Lunix",
    handle: "@SolLunix",
    image: "/Team/sollunix.jpg",
    category: "EARLY OFFICIAL BADGE",
    statusBadge: "EARLY OFFICIAL BADGE",
    followers: "~99K",
    bio: "Crypto Journalist - The world is in our hands 🌎 | @world_xyz @lunixandvoided",
    worldContext: "World posted: \"best badge in the world @SolLunix\" on 26 June 2026. Crypto journalist used in the first public badge drop before launch; not staff.",
    xUrl: "https://x.com/SolLunix",
    sectionId: "first-wave",
  },
  {
    id: "marccolcer",
    name: "Marc Colcer",
    handle: "@marccolcer",
    image: "/Team/marccolcer.jpg",
    category: "EARLY OFFICIAL BADGE",
    statusBadge: "EARLY OFFICIAL BADGE",
    followers: "~50K",
    bio: "Creator, podcaster, photographer.",
    worldContext: "World posted: \"best badge in the world @marccolcer\" on 27 June 2026. Part of the first five-badge wave. Media affiliate, not staff.",
    xUrl: "https://x.com/marccolcer",
    sectionId: "first-wave",
  },
  {
    id: "youknoweno",
    name: "Eno",
    handle: "@YouKnowEno",
    image: "/Team/youknoweno.jpg",
    category: "BADGE HOLDER / ECOSYSTEM CALL",
    statusBadge: "BADGE  VERIFY LIVE",
    followers: "~6.9K",
    bio: "Superteam North Korea joke title, showrunner at @EcosystemCall.",
    worldContext: "World posted on 2 September 2026: \"goes for @YouKnowEno as well  you have a week to create some fire world content or the badge comes off.\" Content affiliation.",
    xUrl: "https://x.com/YouKnowEno",
    sectionId: "ecosystem-call",
  },
  {
    id: "simonmolitor",
    name: "simon (blkn/acc)",
    handle: "@simonmolitor",
    image: "/Team/simonmolitor.jpg",
    category: "ECOSYSTEM CALL / BADGE AFFILIATE",
    statusBadge: "ECOSYSTEM CALL",
    followers: "~9.6K",
    bio: "showrunner at @ecosystemcall, co-founder @solanaidentity, Lucid Drakes, Superteam BLKN member #1.",
    worldContext: "World publicly discussed whether to remove Simon's badge due to lack of World content. Public Solana work in identity & Ecosystem Call.",
    xUrl: "https://x.com/simonmolitor",
    sectionId: "ecosystem-call",
  },
  {
    id: "hoonigall",
    name: "HOON",
    handle: "@HOONIGALL",
    image: "/Team/hoonigall.jpg",
    category: "ECOSYSTEM CALL / CREATIVE AFFILIATE",
    statusBadge: "BADGE  VERIFY LIVE",
    followers: "~16.8K",
    bio: "I drive fast, but i make AI videos faster. AI generative team at @EcosystemCall, creative partner @higgsfield.",
    worldContext: "Video and campaign creative partner. Confirm live badge on X before treating status as active.",
    xUrl: "https://x.com/HOONIGALL",
    sectionId: "ecosystem-call",
  },
  {
    id: "recchoo",
    name: "Reccho",
    handle: "@Recchoo",
    image: "/Team/recchoo.jpg",
    category: "WORLD-ALIGNED CT",
    statusBadge: "WORLD-ALIGNED",
    followers: "~44K",
    bio: "plotting + @world_xyz",
    worldContext: "Posts directly under World, called World \"best marketing\" and replied \"Badge looking good\" on World threads.",
    xUrl: "https://x.com/Recchoo",
    sectionId: "world-aligned",
  },
  {
    id: "sandyxbt",
    name: "Sandy",
    handle: "@sandyXBT",
    image: "/Team/sandyxbt.jpg",
    category: "WORLD-ALIGNED CRYPTO CREATOR",
    statusBadge: "WORLD-ALIGNED",
    followers: "~66K",
    bio: "Crypto, Web3, market insights. NFA.",
    worldContext: "Posted on 5 September that a World follow is priceless. Encouraged creators to make World content for campaign visibility.",
    xUrl: "https://x.com/sandyXBT",
    sectionId: "world-aligned",
  },
  {
    id: "wallstreetalfa",
    name: "WallStreetAlpha",
    handle: "@WallStreetAlfa",
    image: "/Team/wallstreetalfa.jpg",
    category: "RECENT CONFIRMED BADGE",
    statusBadge: "CONFIRMED BADGE",
    followers: "~200K",
    bio: "high-conviction bets and research. $30k to $1m challenge active.",
    worldContext: "Posted on 5 September: \"just received this badge... still don't know what world is.\" World quote-posted as \"world street bets\".",
    xUrl: "https://x.com/WallStreetAlfa",
    sectionId: "world-aligned",
  },
  {
    id: "ministerr",
    name: "Minister",
    handle: "@Ministerr",
    image: "/Team/ministerr.jpg",
    category: "LARGE CT TRADER / BADGE CULTURE",
    statusBadge: "BADGE  VERIFY LIVE",
    followers: "~171K",
    bio: "making internet money with internet friends | Trading | @OKX",
    worldContext: "Replied \"can i get 2?\" under World badge giveaway post. Verify live badge before assuming current status.",
    xUrl: "https://x.com/Ministerr",
    sectionId: "solana-ct",
  },
  {
    id: "fabianosolana",
    name: "fabiano.sol",
    handle: "@FabianoSolana",
    image: "/Team/fabinosolana.jpg",
    category: "SOLANA DEFI CREATOR",
    statusBadge: "BADGE  VERIFY LIVE",
    followers: "~83K",
    bio: "Making a living with Defi.",
    worldContext: "Solana-native DeFi creator in badge distribution ecosystem. Not a published protocol contributor.",
    xUrl: "https://x.com/FabianoSolana",
    sectionId: "solana-ct",
  },
  {
    id: "voided",
    name: "voided",
    handle: "@voided",
    image: "/Team/voided.jpg",
    category: "SOLANA CT / WORLD CONTENT CIRCLE",
    statusBadge: "BADGE  VERIFY LIVE",
    followers: "~93K",
    bio: "on the verge of greatness.",
    worldContext: "Lunix lists @lunixandvoided alongside @world_xyz. Solana CT trading and campaign commentary.",
    xUrl: "https://x.com/voided",
    sectionId: "solana-ct",
  },
  {
    id: "defidarling",
    name: "sara",
    handle: "@defidarling",
    image: "/Team/defidarling.jpg",
    category: "SOLANA / CT SIGNAL ACCOUNT",
    statusBadge: "BADGE  VERIFY LIVE",
    followers: "~93K",
    bio: "your favourite top signal.",
    worldContext: "Market signals / CT account. Affiliation badge supplied by research; not research staff.",
    xUrl: "https://x.com/defidarling",
    sectionId: "solana-ct",
  },
  {
    id: "gumsays",
    name: "gum",
    handle: "@gumsays",
    image: "/Team/gumsays.jpg",
    category: "DIGITAL FINANCE / SOLANA MARKETS",
    statusBadge: "BADGE  VERIFY LIVE",
    followers: "~67K",
    bio: "Digital finance / data / investments. repetition is reputation.",
    worldContext: "Digital finance / data on Kamino & yield. Badge affiliation supplied by research; not World employee.",
    xUrl: "https://x.com/gumsays",
    sectionId: "solana-ct",
  },
  {
    id: "radtrades_",
    name: "Rad",
    handle: "@RadTrades_",
    image: "/Team/radtrades_.jpg",
    category: "SOLANA CT TRADER",
    statusBadge: "BADGE  VERIFY LIVE",
    followers: "~27K",
    bio: "impossible is an opinion.",
    worldContext: "Solana CT trader. Affiliation badge supplied by research; verify live profile.",
    xUrl: "https://x.com/RadTrades_",
    sectionId: "other-affiliates",
  },
  {
    id: "masterchiefnfts",
    name: "MasterChief",
    handle: "@MasterChiefNFTs",
    image: "/Team/masterchiefNFTs.jpg",
    category: "SOLANA COMPANY-BUILDER / MEME ACCOUNT",
    statusBadge: "BADGE  VERIFY LIVE",
    followers: "~31K",
    bio: "growing crypto companies at @stratospherevip, memes @bloodlineFNF, co-founded @apcollective.",
    worldContext: "Solana company growth and crypto culture. Badge affiliation supplied by research.",
    xUrl: "https://x.com/MasterChiefNFTs",
    sectionId: "other-affiliates",
  },
  {
    id: "sunnymaanz",
    name: "Sunny",
    handle: "@sunnymaanz",
    image: "/Team/sunnymaanz.jpg",
    category: "CRYPTO GROWTH / MARKETING",
    statusBadge: "BADGE  VERIFY LIVE",
    followers: "~23K",
    bio: "crypto changed my life, now I help the best companies in the industry make the internet care.",
    worldContext: "Marketing & growth storytelling. Affiliation; do not call Sunny World CMO.",
    xUrl: "https://x.com/sunnymaanz",
    sectionId: "other-affiliates",
  },
  {
    id: "loganlim_x",
    name: "Logan Lim",
    handle: "@loganlim_x",
    image: "/Team/loganlim_x.jpg",
    category: "FOMO / CONVICTION CIRCLE",
    statusBadge: "BADGE  VERIFY LIVE",
    followers: "~6K",
    bio: "Logan Lim on @fomo, member of @Convictioncap_.",
    worldContext: "Part of FOMO / Conviction ecosystem. World referenced 7-figure PnL badge rule on @fomo.",
    xUrl: "https://x.com/loganlim_x",
    sectionId: "other-affiliates",
  },
  {
    id: "solanasensei",
    name: "Solana Sensei",
    handle: "@SolanaSensei",
    image: "/Team/solanasenei.jpg",
    category: "TEMPORARY / LAUNCH SUPPORT",
    statusBadge: "TEMPORARY / NOT WORLD STAFF",
    followers: "~253K",
    bio: "Solana OG. Founder & CEO of Sensei Holdings and Namaste Group.",
    worldContext: "Wore the World badge for ~2 days before launch. On 3 July 2026 he explicitly stated he wore it temporarily to support the launch campaign, was unpaid, and is NOT part of the World team.",
    xUrl: "https://x.com/SolanaSensei",
    sectionId: "temporary-support",
  },
];

export const TEAM_SECTIONS = [
  { id: "official", subtitle: "Anchor account for World badge campaign" },
  { id: "house-face", subtitle: "Public mascot & frontman identified by World" },
  { id: "first-wave", subtitle: "Early creators tagged by World in June 2026" },
  { id: "ecosystem-call", subtitle: "Content showrunners & campaign creative partners" },
  { id: "world-aligned", subtitle: "High-conviction market research & loud supporters" },
  { id: "solana-ct", subtitle: "Solana-native trading, signals & DeFi creators" },
  { id: "other-affiliates", subtitle: "Crypto growth, company builders & trading accounts" },
  { id: "temporary-support", subtitle: "Early campaign support; explicitly not World staff" },
];
